### ISSUE TITLE
Player can't move

### ISSUE THREAD

**Issue by PancakeSparkle** [JoshuaWierenga/Game-that-does-not-have-a-name-yet#29]
Cannot move unless i jump first and player keeps going to starting position,lives don't change after dying,there are 2 players instead of just one.

**Comment by JoshuaWierenga** [comment]
I broke it even more :)
[![Video](http://img.youtube.com/vi/Rv-48wTPDeg/mqdefault.jpg)](https://www.youtube.com/watch?v=Rv-48wTPDeg)
click to see more

**Comment by JoshuaWierenga** [comment]
go check #30 Movement is fixed

**Comment by JoshuaWierenga** [comment]
now twice the videos about broken content
[![Video](http://img.youtube.com/vi/dwWS6J6jfVw/mqdefault.jpg)](https://www.youtube.com/watch?v=dwWS6J6jfVw&feature=youtu.be)
click for video
