### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by JoshuaWierenga** [JoshuaWierenga/Game-that-does-not-have-a-name-yet#33]
@joshuaw-beta-testers/testers Any features you would like to see?
If you have game maker you can add them your self if you know how.

**Comment by JoshuaWierenga** [comment]
no idea what happened ^

**Comment by Mishchap** [comment]
same here​

On 20 July 2015 at 16:25, Joshua Wierenga notifications@github.com wrote:

> no idea what happened ^
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joshuaw-beta-testers/Game-that-does-not-have-a-name-yet/issues/33#issuecomment-122774160
> .

## 

Sent from me

**Comment by JoshuaWierenga** [comment]
@joshuaw-beta-testers/testers you going to do anything?

**Comment by JoshuaWierenga** [comment]
@joshuaw-beta-testers/testers you going to do anything? or do i need to get better testers who do stuff!

**Comment by JoshuaWierenga** [comment]
I went and renamed the next release to 0.1 from 0.0.4 as it is getting closer to a game

**Comment by JoshuaWierenga** [comment]
@joshuaw-beta-testers/testers are you going to suggest anything?
im adding all i can think of but i would like you to come up with a few things.

**Comment by JoshuaWierenga** [comment]
Things i am working on
[ ] enemy movement
[ ] player movement

**Comment by JoshuaWierenga** [comment]
Things i am working on
- [ ] enemy movement
- [ ] player movement

**Comment by JoshuaWierenga** [comment]
@joshuaw-game-alpha-testers/testers  anything else you think i should add
