### ISSUE TITLE
BUGZEZZEZEEIJIAZZJXJIIXJAXO!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by ghost** [JoshuaWierenga/Game-that-does-not-have-a-name-yet#45]
Bugs I've found so far:
The player sometimes flips/falls over. Jumping on the green slime thing will make it fall over too.
The spawn is in a fixed place. For example, when you transition from one level/stage to the one on the left, your player will still spawn in the same place as if you went left to right.
If you continue running left or right, sometimes the players legs will remain in a "stand" position.
After the slime stage, the next level is a void. If you try to go back to the slime stage, your character will get lost and you will stay in the void forever D: !!!!

**Comment by JoshuaWierenga** [comment]
what are you falling on

**Comment by JoshuaWierenga** [comment]
- [x] The player sometimes flips/falls over. 
  
    now that there are no hills i dont think this can happen
    if it does, comment on this with details about where it does
- [x] Jumping on the green slime thing will make it fall over too.
  
    does that still happen in the new version with the flat ground?
- [ ] The spawn is in a fixed place. For example, when you transition from one level/stage to the one on the left, your player will still spawn in the same place as if you went left to right.
  
     ???????????
- [ ] If you continue running left or right, sometimes the players legs will remain in a "stand" position.
  
  if you mean on level one you are still moving but the level is blank so it looks like nothing is moving       
- [ ] After the slime stage, the next level is a void. If you try to go back to the slime stage, your character will get lost and you will stay in the void forever D: !!!!
  
  im asuming by void you mean area outside of level 
     if so that is fixed now as i added walls around level

**Comment by JoshuaWierenga** [comment]
@Ravironio you want these fixed or not?
need more details!
